### ISSUE TITLE
inconsistencies in lambert lighting in problems light-2 and light-3

### ISSUE THREAD

**Issue by andyhall** [stackgl/shader-school#111]
In the answer code for problems "Light 2" and "Light 3", there are inconsistencies with how the Lambert brightness term is calculated:

* Both answers include code like `dot( fragNorm, lightDir)`, where `fragNorm` is passed in from the vertex shader. But in "Light 2" `fragNorm` is in world coordinates and in "Light 3" it's in view coordinates.
* The answer code for "Light 2" clamps the brightness term to be >= 0 (using `max`), but the answer code for "Light 3" doesn't.

If I understand the lessons I think the version in Light 2 is the correct one, and the Light 3 answer code should be changed to fix these two inconsistencies. But being new to GLSL I'm not sure.

**Comment by acruikshank** [comment]
I'm with @andyhall on this one. It took me spending a long time and digging through the source to arrive at what I believe is a less correct answer.

**Comment by mikolalysenko** [comment]
Yeah, it is definitely a problem.  @hughsk and I have some time blocked out in early march to dig through the issues and get this cleaned up, but both of us are too busy to take on this work right now.

**Comment by andyhall** [comment]
@mikolalysenko , keep in mind that for a lot of these, somebody else might be willing to implement the fix if an expert can chime in on what needs to be done! It's the nature of the project that the people who find the bugs and are willing to make a PR probably don't know what the correct behavior is.

**Comment by mikolalysenko** [comment]
Fixed.  @andyhall yeah, if you want to help out you can send some PRs.  @hughsk  and I are hacking on shader-school/webgl-workshop today and gonna try to get through the backlog.
