### ISSUE TITLE
Four lessons render no output

### ISSUE THREAD

**Issue by andyhall** [stackgl/shader-school#112]
Perhaps I'm missing something, but I find that lessons 20-23 (lighting 4&5, cel shading, gooch shading) don't render any model (neither the "expected" nor the user-defined versions).

The two lighting lessons (4&5) render squares flying around (which I take to be the point lights), but the Stanford dragon doesn't render at all. (Sometimes it shows up for a moment when refreshing the browser.) 

For the two shading lessons (npr 1&2), no GLSL output renders at all. Just the lesson UI.

Lessons 24 (game of life) and onwards appear to work normally.

This is all for a fresh install of shader-school, without any edits to the user versions of the scripts.

**Comment by hapticdata** [comment]
I am experiencing the same thing, "Point Lights" and "Multiple Lights" render the colored squares only, and the "Cel Shading" and "Gooch Shading" render nothing in Chrome Version 40.0.2214.115 (64-bit) on a MacBook Pro with NVIDIA GeForce GT 650M.

However, the same lessons work correctly in Safari v8.0.3.
Output missing completely in FireFox 34-36.


--
Thanks for all of the hard work on this awesome project, it is very appreciated!

**Comment by mikolalysenko** [comment]
Thanks for the report, will look into this next week.

**Comment by mikolalysenko** [comment]
Fixed
