### ISSUE TITLE
after setup,the browser is blank, having no menu

### ISSUE THREAD

**Issue by tyrantgit** [stackgl/shader-school#115]
cannot access any lesson

**Comment by mipearson** [comment]
I had this problem myself installing  via npm. Grabbed the github repo to try to work out the problem. Found that master (as at 2015/02/01) works, but v1.0.2 does not. So _something_ has fixed it..

**Comment by mipearson** [comment]
Ah. It would have been fixed by the browserify upgrade, https://github.com/stackgl/shader-school/issues/58

**Comment by tyrantgit** [comment]
problem solved,thank you
