### ISSUE TITLE
geom-5 expected = geom-4 expected

### ISSUE THREAD

**Issue by randompast** [stackgl/shader-school#116]
https://github.com/stackgl/shader-school/blob/master/exercises/geom-5/shaders/expected.glsl

**Comment by sudodoki** [comment]
@randompast points to the fact that https://github.com/stackgl/shader-school/blob/master/exercises/geom-5/shaders/expected.glsl is same as https://github.com/stackgl/shader-school/blob/master/exercises/geom-4/shaders/expected.glsl

**Comment by mikolalysenko** [comment]
Fixed
