### ISSUE TITLE
intro-6 wrong answer given for mat multiplication example

### ISSUE THREAD

**Issue by jarav** [stackgl/shader-school#122]
In the content for this lesson, towards the end this is given:

mat2 m = mat2(1, 2,  3, 4);

vec2 v = m * vec2(1, 2);  //v = vec2(5, 8)

The answer should be //v = vec2(7, 10)

Also in this line:

vec2 u = vec2(1, 2) * m;  //u = vec2(7, 10)

The answer should be //u = vec2(5, 11)

**Comment by abacon** [comment]
FYI: Duplicate of #137. There's an outstanding PR, #138.
