### ISSUE TITLE
Intro 2- Qualifiers and Built-Ins 

### ISSUE THREAD

**Issue by pm0355** [stackgl/shader-school#123]
So I hit a roadblock in coding the second exercise. The variables are not constant so they can update, the math is alright I think, but I am still not getting a clear on Qualifiers and Built-Ins. Here is my code,

![screen shot 2015-03-14 at 9 11 40 pm](https://cloud.githubusercontent.com/assets/7031539/6654270/bfc7a304-ca8e-11e4-99de-a52a8aede4d6.png)

any help would be super appreciated.

**Comment by mikolalysenko** [comment]
you need to declare opposite and adjacent as `out` type

**Comment by pm0355** [comment]
thanks, got it now!
