### ISSUE TITLE
Install failed on Mac OSX 

### ISSUE THREAD

**Issue by TimothyStiles** [stackgl/shader-school#147]
Tried installing with NPM and this is what I got while using <code>node 0.12.6</code>

<code>npm WARN deprecated rework-inline@0.2.0: deprecated in favor of rework-import
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"0.12.6","npm":"3.3.5"})
npm WARN install Couldn't install optional dependency: Registry returned 404 for GET on https://registry.npmjs.org/esprima-six </code>

Tried installing with <code>node 0.8.28</code> and got this debug log.

https://gist.github.com/TimothyStiles/6f29923d56b5543bff93

Hope this helps the maintainers!

**Comment by nchase** [comment]
@TimothyStiles: this issue is being tracked in #145.

**Comment by mattdesl** [comment]
resolved, see: https://github.com/stackgl/shader-school/issues/145#issuecomment-168851132
