### ISSUE TITLE
esprima six

### ISSUE THREAD

**Issue by niteswim** [stackgl/shader-school#149]
getting this error:

npm WARN deprecated rework-inline@0.2.0: deprecated in favor of rework-import
npm WARN engine pngjs@0.4.0: wanted: {"node":"0.8.x"} (current: {"node":"5.1.0","npm":"3.3.12"})
npm WARN install Couldn't install optional dependency: Registry returned 404 for GET on https://registry.npmjs.org/esprima-six

on os x 10.11.1

**Comment by nchase** [comment]
@niteswim: this issue is being tracked in #145

**Comment by mattdesl** [comment]
I pushed a hot fix to npm with `glslify@1.6.1` which should fix installs. Let me know if there are more problems.
