### ISSUE TITLE
Failed Install on Windows 7

### ISSUE THREAD

**Issue by 8ude** [stackgl/shader-school#153]
Tried to install on two different machines - both Windows 7, both failed.  Any advice would be appreciated.

Trace:
[npm_output.txt](https://github.com/stackgl/shader-school/files/75999/npm_output.txt)

And the debug log:
[npm-debug-log.txt](https://github.com/stackgl/shader-school/files/75996/npm-debug-log.txt)

**Comment by mattdesl** [comment]
I pushed a hot fix to npm with `glslify@1.6.1` which should fix installs. Let me know if there are more problems.

**Comment by 8ude** [comment]
Thanks Matt.  But .. now I'm getting errors that I don't have git installed (I do.  Git and github are working properly for me).  

Does git need to be installed or copied into a certain path?  I'm not having this issue on other nodeschool modules...

[npm-debug.txt](https://github.com/stackgl/shader-school/files/107447/npm-debug.txt)
