### ISSUE TITLE
Lesson 10 - Wrongly defines rotation matrix in row major form.

### ISSUE THREAD

**Issue by esiegel** [stackgl/shader-school#73]
I'm new to GLSL, but it seems that we should specify the translation matrix in column major order:

```glsl
  mat2 rot = mat2(c, -s, s, c);
```

**Comment by mikolalysenko** [comment]
I'm not sure what the issue is here, but transposing a rotation matrix just changes whether it rotates forward or in reverse.  In this case the behavior seems reasonable.  Perhaps you could elaborate on what you find confusing?
