### ISSUE TITLE
Intro-06: Solution is unexpected

### ISSUE THREAD

**Issue by julescarbon** [stackgl/shader-school#79]
Coming out of a section on loops, I expected to use a for loop here.  Instead, this was a lesson about a GLSL "gotcha" -- you can't use uniforms as part of the conditional clause of a for loop.  But uniforms have not even been introduced yet.

The expected solution is frustrating to see -- it's more about adding exponents than multiplication.  The bit about matrixCompMult feels like a red herring.

**Comment by hughsk** [comment]
Closing in favour of #104 :)
